# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #   monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'img-service'
    # resp_time = rate(predict_millseconds_sum[5m]) / rate(predict_millseconds_count[5m]) 
    metrics_path: /metrics
    static_configs:
      - targets: ['10.10.200.105:9527']
  - job_name: 'img-triger'
    metrics_path: /img/random
    static_configs:
      - targets: ['10.10.200.105:9527']
